# Generated by Django 3.2.19 on 2023-06-27 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='caption',
            new_name='heading',
        ),
    ]
